Repository icyleaf/swagger, pull requests merged in 2020-02, with the labels that each got.

#5 Add parameter location enum
  .circleci/config.yml
  examples/authorization.cr
  examples/frameworks/kemal.cr
  examples/simple.cr
  spec/swagger/controller_spec.cr
  spec/swagger/objects/components_spec.cr
  spec/swagger/objects/parameter_spec.cr
  spec/swagger/objects/security_scheme_spec.cr
  src/swagger/objects/operation.cr
  src/swagger/objects/parameter.cr
Labels: ✅ Approved

#9 Use jsdeliver cdn
  src/swagger/http/assets/swagger-ui/favicon-16x16.png
  src/swagger/http/assets/swagger-ui/favicon-32x32.png
  src/swagger/http/assets/swagger-ui/swagger-ui-bundle.js
  src/swagger/http/assets/swagger-ui/swagger-ui-standalone-preset.js
  src/swagger/http/assets/swagger-ui/swagger-ui.css
  src/swagger/http/views/oauth2-redirect.html
  src/swagger/http/views/swagger.ecr
Labels: enhancement, ✅ Approved

#7 Make response mandatory
  examples/authorization.cr
  examples/frameworks/kemal.cr
  examples/simple.cr
  spec/swagger/action_helper.cr
  spec/swagger/action_spec.cr
  spec/swagger/controller_spec.cr
  spec/swagger/objects/operation_spec.cr
  spec/swagger/objects/path_item_spec.cr
  spec/swagger/objects/response_helper.cr
  src/swagger/action.cr
  src/swagger/controller.cr
  src/swagger/objects/encoding.cr
  src/swagger/objects/media_type.cr
  src/swagger/objects/operation.cr
  src/swagger/objects/parameter.cr
  src/swagger/objects/path_item.cr
  src/swagger/objects/request_body.cr
  src/swagger/objects/response.cr
  src/swagger/objects/schema.cr
  src/swagger/response.cr
Labels: ✅ Approved

#10 Move OpenAPI version to Document
  src/swagger.cr
  src/swagger/http/handlers/api.cr
  src/swagger/objects/document.cr
Labels: ✅ Approved

#11 Bump OpenAPI version to 3.0.3
  src/swagger/objects/components.cr
  src/swagger/objects/document.cr
  src/swagger/objects/encoding.cr
  src/swagger/objects/example.cr
  src/swagger/objects/external_docs.cr
  src/swagger/objects/header.cr
  src/swagger/objects/info.cr
  src/swagger/objects/link.cr
  src/swagger/objects/media_type.cr
  src/swagger/objects/operation.cr
  src/swagger/objects/parameter.cr
  src/swagger/objects/path_item.cr
  src/swagger/objects/request_body.cr
  src/swagger/objects/response.cr
  src/swagger/objects/schema.cr
  src/swagger/objects/security_scheme.cr
  src/swagger/objects/server.cr
  src/swagger/objects/tag.cr
Labels: 🔍 Ready for Review

#12 Release 0.2.0
  CHANGELOG.md
  README.md
  shard.yml
Labels: 🔍 Ready for Review
